name: Deploy Web to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        working-directory: _/apps/web
        run: npm ci

      - name: Build
        working-directory: _/apps/web
        run: npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Vite in this repo outputs to build/client — publish that folder
          publish_dir: _/apps/web/build/client
          publish_branch: gh-pages
          allow_empty_commit: false
